/* ==========================================================================
   VIZAG EXPRESS — UI
   Renders every section from js/data.js and wires up the CSS-3D interactions
   (crew carousel, tilt cards, flip cards, scroll-driven route map).
   The static HTML (generated by tools/seo.js) already contains all the content;
   this upgrades it right after the first paint, so text shows without waiting on JS.
   ========================================================================== */
const boot = () => {
  "use strict";

  const { TRIP, MEMBERS, ROLES, PLACES, EVENTS } = window;
  const UPCOMING = window.UPCOMING_PLACE_SLOTS || 0;

  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const esc = (s) =>
    String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
  const reduceMotion = matchMedia("(prefers-reduced-motion: reduce)").matches;
  const finePointer = matchMedia("(hover: hover) and (pointer: fine)").matches;

  /* ------------------------------------------------------------------ icons */
  const svg = (p) =>
    `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p}</svg>`;
  const ICONS = {
    train: svg('<path d="M8 3.1V7a4 4 0 0 0 8 0V3.1"/><path d="m9 15-1-1"/><path d="m15 15 1-1"/><path d="M9 19c-2.8 0-5-2.2-5-5v-4a8 8 0 0 1 16 0v4c0 2.8-2.2 5-5 5Z"/><path d="m8 19-2 3"/><path d="m16 19 2 3"/>'),
    arrow: svg('<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>'),
    chevL: svg('<path d="m15 18-6-6 6-6"/>'),
    chevR: svg('<path d="m9 18 6-6-6-6"/>'),
    ticket: svg('<path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z"/><path d="M13 5v2"/><path d="M13 17v2"/><path d="M13 11v2"/>'),
    pin: svg('<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>'),
    calc: svg('<rect width="16" height="20" x="4" y="2" rx="2"/><path d="M8 6h8"/><path d="M16 14v4"/><path d="M16 10h.01"/><path d="M12 10h.01"/><path d="M8 10h.01"/><path d="M12 14h.01"/><path d="M8 14h.01"/><path d="M12 18h.01"/><path d="M8 18h.01"/>'),
    wallet: svg('<path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 5v14a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a2 2 0 0 0 0 4h4v-4Z"/>'),
    sparkles: svg('<path d="m12 3-1.9 5.8a2 2 0 0 1-1.3 1.3L3 12l5.8 1.9a2 2 0 0 1 1.3 1.3L12 21l1.9-5.8a2 2 0 0 1 1.3-1.3L21 12l-5.8-1.9a2 2 0 0 1-1.3-1.3Z"/><path d="M5 3v4"/><path d="M3 5h4"/><path d="M19 17v4"/><path d="M17 19h4"/>'),
    cards: svg('<rect x="8" y="2" width="12" height="17" rx="2"/><path d="M8 6.5 4.6 7.4a2 2 0 0 0-1.4 2.4l3 11.3a2 2 0 0 0 2.4 1.4L15 21"/><path d="M14 7.5c-1.4 1.6-2.4 2.7-2.4 3.9a2.4 2.4 0 0 0 4.8 0c0-1.2-1-2.3-2.4-3.9Z"/>'),
    uno: svg('<rect x="5" y="2" width="14" height="20" rx="2.5"/><ellipse cx="12" cy="12" rx="4" ry="6.5" transform="rotate(28 12 12)"/>'),
    video: svg('<path d="m16 13 5.2 3.5a.5.5 0 0 0 .8-.4V7.9a.5.5 0 0 0-.8-.4L16 10.5"/><rect x="2" y="6" width="14" height="12" rx="2"/>'),
    camera: svg('<path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"/><circle cx="12" cy="13" r="3"/>'),
    users: svg('<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>'),
    route: svg('<circle cx="6" cy="19" r="3"/><path d="M9 19h8.5a3.5 3.5 0 0 0 0-7h-11a3.5 3.5 0 0 1 0-7H15"/><circle cx="18" cy="5" r="3"/>'),
    flag: svg('<path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><path d="M4 22v-7"/>'),
    bulb: svg('<path d="M9 18h6"/><path d="M10 22h4"/><path d="M12 2a7 7 0 0 0-4 12.7V16h8v-1.3A7 7 0 0 0 12 2Z"/>'),
    waves: svg('<path d="M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"/><path d="M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"/><path d="M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"/>'),
    clock: svg('<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>'),
    volume: svg('<path d="M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z"/><path d="M16 9a5 5 0 0 1 0 6"/><path d="M19.364 18.364a9 9 0 0 0 0-12.728"/>'),
  };

  // sound effects (js/sound.js); silently does nothing when sound is off
  const sfx = (name, opts) => window.SFX && window.SFX.play(name, opts);
  const hydrateIcons = (root = document) =>
    $$("[data-icon]", root).forEach((el) => {
      if (!el.firstElementChild) el.innerHTML = ICONS[el.dataset.icon] || "";
    });

  /* ---------------------------------------------------------------- members */
  const HUES = [18, 205, 265, 150, 330, 42, 175, 95, 290];
  const byId = {};
  MEMBERS.forEach((m, i) => {
    const words = m.name.trim().split(/\s+/);
    m.initials = (words[0][0] + (words.length > 1 ? words[words.length - 1][0] : "")).toUpperCase();
    m.hue = HUES[i % HUES.length];
    m.seat = String(i + 1).padStart(2, "0");
    byId[m.id] = m;
  });
  const rolesOf = (id) =>
    ROLES.flatMap((r) => {
      const entry = r.members.find((x) => x.id === id);
      return entry ? [{ role: r, note: entry.note }] : [];
    });
  const eventTeam = (ROLES.find((r) => r.id === "event") || { members: [] }).members.map((e) => byId[e.id]).filter(Boolean);
  const placeTeam = (ROLES.find((r) => r.id === "place") || { members: [] }).members.map((e) => byId[e.id]).filter(Boolean);

  const avatar = (m, cls = "h-10 w-10 text-sm") =>
    `<span class="avatar ${cls}" style="--h:${m.hue}" data-member="${esc(m.id)}" title="${esc(m.name)}"><span class="initials">${esc(m.initials)}</span></span>`;
  const avatarStack = (list, cls = "h-8 w-8 text-[10px]") => list.map((m) => avatar(m, cls)).join("");

  // Photos: assets/members/<id>.(jpg|jpeg|png|webp), or an explicit `photo` path in data.js
  const EXTS = ["jpg", "jpeg", "png", "webp"];
  const photoCache = {};
  const findPhoto = (id) =>
    (photoCache[id] ||= new Promise((resolve) => {
      const m = byId[id];
      const optimized = window.PHOTOS && window.PHOTOS[id]; // from `npm run photos`
      if (window.PHOTOS && window.PHOTOS[id] === null) return resolve(null); // known: no photo yet
      const list = optimized ? [optimized] : m && m.photo ? [m.photo] : EXTS.map((e) => `assets/members/${id}.${e}`);
      let i = 0;
      const next = () => {
        if (i >= list.length) return resolve(null);
        const src = list[i++];
        const probe = new Image();
        probe.onload = () => resolve(src);
        probe.onerror = next;
        probe.src = src;
      };
      next();
    }));
  const hydratePhotos = (root = document) =>
    $$(".avatar[data-member]:not([data-hydrated])", root).forEach((el) => {
      el.dataset.hydrated = "1";
      findPhoto(el.dataset.member).then((src) => {
        if (!src) return;
        const img = new Image();
        img.src = src;
        // the big crew-card photos carry the name (image search); small repeats stay decorative
        img.alt = el.classList.contains("crew-photo") ? byId[el.dataset.member].name : "";
        img.decoding = "async";
        img.draggable = false;
        el.appendChild(img);
        el.classList.add("has-photo");
      });
    });

  /* ------------------------------------------------------------ text binds */
  $$("[data-bind]").forEach((el) => {
    const v = el.dataset.bind.split(".").reduce((o, k) => (o == null ? o : o[k]), TRIP);
    if (v != null) el.textContent = v;
  });

  /* ------------------------------------------------------------------ hero */
  $("#hero-crew").innerHTML = avatarStack(MEMBERS, "h-10 w-10 text-xs");

  /* ----------------------------------------------------------------- stats */
  const STATS = [
    { n: MEMBERS.length, label: "Travellers", icon: "users" },
    { n: TRIP.distanceKm, pre: "~", post: " km", label: "On the rails", icon: "route" },
    { n: ROLES.length, label: "Crew teams", icon: "flag" },
    { n: PLACES.length, label: PLACES.length === 1 ? "Place so far" : "Places so far", icon: "pin" },
    { n: EVENTS.length, label: "Activities", icon: "sparkles" },
  ];
  $("#stats").innerHTML = STATS.map(
    (s) => `
    <div class="stat">
      <span class="text-amber-300">${ICONS[s.icon]}</span>
      <p class="mt-3 whitespace-nowrap font-display text-3xl font-extrabold sm:text-2xl md:text-3xl lg:text-4xl">${s.pre || ""}<span data-count="${s.n}">${reduceMotion ? s.n : 0}</span>${s.post || ""}</p>
      <p class="mt-1 text-xs uppercase tracking-[0.18em] text-slate-400">${s.label}</p>
    </div>`
  ).join("");

  const runCounters = () =>
    $$("[data-count]").forEach((el) => {
      const end = +el.dataset.count;
      if (reduceMotion) return (el.textContent = end);
      const t0 = performance.now();
      const dur = 1400;
      const step = (t) => {
        const k = Math.min(1, (t - t0) / dur);
        el.textContent = Math.round(end * (1 - Math.pow(1 - k, 3)));
        if (k < 1) requestAnimationFrame(step);
      };
      requestAnimationFrame(step);
    });

  /* ---------------------------------------------------------------- ticket */
  const depart = TRIP.date ? new Date(TRIP.date) : null;
  const field = (label, value) =>
    `<div><p class="field-label">${label}</p><p class="field-value">${esc(value)}</p></div>`;
  $("#ticket").innerHTML = `
    <article class="tilt ticket" data-tilt="7" aria-label="Boarding pass">
      <div class="ticket-main">
        <div class="ticket-head -mx-7 -mt-7 mb-7 flex items-center justify-between rounded-t-[1.75rem] px-7 py-4 sm:rounded-tr-none">
          <p class="flex items-center gap-2 font-display font-extrabold"><span class="text-amber-300">${ICONS.train}</span>${esc(TRIP.name)}</p>
          <p class="text-[10px] font-semibold uppercase tracking-[0.3em] text-amber-200">Boarding pass</p>
        </div>

        <div class="z-pop-2 flex items-end justify-between gap-3">
          <div>
            <p class="field-label">From</p>
            <p class="font-display text-4xl font-extrabold leading-none sm:text-5xl xl:text-6xl">${esc(TRIP.from.code)}</p>
            <p class="mt-1 text-sm text-slate-600">${esc(TRIP.from.city)}</p>
          </div>
          <div class="mb-7 flex flex-1 items-center gap-2 text-orange-500" aria-hidden="true">
            <span class="ticket-line flex-1"></span>${ICONS.train}<span class="ticket-line flex-1"></span>
          </div>
          <div class="text-right">
            <p class="field-label">To</p>
            <p class="font-display text-4xl font-extrabold leading-none sm:text-5xl xl:text-6xl">${esc(TRIP.to.code)}</p>
            <p class="mt-1 text-sm text-slate-600">${esc(TRIP.to.city)}</p>
          </div>
        </div>

        <div class="z-pop-1 mt-8 grid grid-cols-2 gap-5 sm:grid-cols-4">
          ${field("Date", depart ? depart.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "TBA")}
          ${field("Departs", depart ? depart.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" }) : "TBA")}
          ${field("Train", TRIP.train)}
          ${field("Coach", TRIP.coach)}
        </div>

        <div class="z-pop-1 mt-7 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-900/[0.06] p-3">
          <div class="flex -space-x-2">${avatarStack(MEMBERS, "h-9 w-9 text-[10px] !shadow-[0_0_0_2px_#fdf2e3]")}</div>
          <p class="text-sm font-semibold text-slate-700">${String(MEMBERS.length).padStart(2, "0")} passengers</p>
        </div>
      </div>

      <div class="ticket-stub">
        <div class="z-pop-1 grid grid-cols-2 gap-4 sm:grid-cols-1">
          ${field("Crew code", "VE-" + String(MEMBERS.length).padStart(2, "0"))}
          ${field("Distance", "~" + TRIP.distanceKm + " km")}
          ${field("Duration", "~" + TRIP.durationHrs + " hrs")}
          <div>
            <p class="field-label">Countdown</p>
            <p id="countdown" class="field-value">${depart ? "…" : "Once booked"}</p>
          </div>
        </div>
        <div class="barcode z-pop-1 mt-5" aria-hidden="true"></div>
      </div>
      <div class="glare"></div>
    </article>`;

  if (depart) {
    const cd = $("#countdown");
    const pad = (n) => String(n).padStart(2, "0");
    const tickCountdown = () => {
      const ms = depart - Date.now();
      if (ms <= 0) return (cd.textContent = "All aboard! 🚆");
      const d = Math.floor(ms / 864e5);
      const h = Math.floor((ms % 864e5) / 36e5);
      const m = Math.floor((ms % 36e5) / 6e4);
      const s = Math.floor((ms % 6e4) / 1e3);
      cd.textContent = `${d}d ${pad(h)}h ${pad(m)}m ${pad(s)}s`;
    };
    tickCountdown();
    setInterval(tickCountdown, 1000);
  }

  /* ----------------------------------------------------------------- route */
  const route = $("#route");
  const stops = TRIP.stops;
  route.innerHTML = `
    <div class="route-rail" aria-hidden="true"></div>
    <div class="route-progress" aria-hidden="true"></div>
    <div class="route-train" aria-hidden="true">${ICONS.train}</div>
    <ol class="relative" aria-label="Route stops">
      ${stops
        .map((s, i) => {
          const first = i === 0;
          const last = i === stops.length - 1;
          const sub = first ? "Departure" : last ? "Arrival · end of the line" : s.scenic ? "Scenic stretch" : "En route";
          const badge = s.scenic
            ? `<span class="text-teal-300" title="Scenic">${ICONS.waves}</span>`
            : `<span class="rounded-lg bg-white/5 px-2.5 py-1 font-mono text-xs text-slate-300">${esc(s.code)}</span>`;
          return `
          <li class="stop ${first || last ? "terminal" : ""}">
            <span class="stop-dot" aria-hidden="true"></span>
            <div class="stop-card">
              <div>
                <p class="font-display text-lg font-bold ${first || last ? "text-white" : "text-slate-200"}">${esc(s.name)}</p>
                <p class="text-xs ${s.scenic ? "text-teal-300" : "text-slate-400"}">${sub}</p>
              </div>
              ${badge}
            </div>
          </li>`;
        })
        .join("")}
    </ol>`;

  const stopEls = $$(".stop", route);
  let routeGeo = null;
  const measureRoute = () => {
    const base = route.getBoundingClientRect().top;
    const centers = stopEls.map((li) => {
      const r = $(".stop-dot", li).getBoundingClientRect();
      return r.top + r.height / 2 - base;
    });
    const top = centers[0];
    const len = centers[centers.length - 1] - top;
    route.style.setProperty("--top", top + "px");
    route.style.setProperty("--len", len + "px");
    routeGeo = { top, len, centers };
  };
  let lastStop = null;
  const updateRoute = () => {
    if (!routeGeo) measureRoute();
    const { top, len, centers } = routeGeo;
    const line = innerHeight * 0.55 - route.getBoundingClientRect().top;
    const p = Math.min(1, Math.max(0, (line - top) / len));
    route.style.setProperty("--p", p.toFixed(4));
    const y = top + p * len;
    let current = -1;
    stopEls.forEach((li, i) => {
      const passed = centers[i] <= y + 2;
      li.classList.toggle("passed", passed);
      if (passed) current = i;
    });
    stopEls.forEach((li, i) => li.classList.toggle("current", i === current));
    if (lastStop !== null && current > lastStop) {
      const arrived = current === stopEls.length - 1;
      sfx(arrived ? "chime" : "ping", { volume: arrived ? 0.5 : 0.3, rate: arrived ? 1 : 0.85 + current * 0.06, throttle: 110 });
    }
    lastStop = current;
  };

  /* ------------------------------------------------------------ crew ring */
  const initCrew = () => {
    const stage = $("#crew-stage");
    const ring = $("#crew-ring");
    const dots = $("#crew-dots");
    const detail = $("#crew-detail");
    const n = MEMBERS.length;
    const step = 360 / n;

    ring.innerHTML = MEMBERS.map(
      (m, i) => `
      <div class="crew-card" style="--a:${i * step}deg" data-i="${i}">
        <div class="crew-face crew-front">
          ${avatar(m, "crew-photo")}
          <span class="absolute left-3 top-3 rounded-full bg-night-950/70 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-amber-200 backdrop-blur">Seat ${m.seat}</span>
          <div class="crew-card-info">
            <p class="font-display text-base font-extrabold leading-tight sm:text-xl">${esc(m.name)}</p>
            <p class="mt-1 text-[11px] text-slate-300 sm:text-xs">${rolesOf(m.id)
              .map((r) => r.role.title.split(" /")[0])
              .join(" · ")}</p>
          </div>
        </div>
        <div class="crew-face crew-back" aria-hidden="true">
          <div class="text-center">
            <span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-amber-300 to-rose-500 text-night-950">${ICONS.train}</span>
            <p class="mt-3 font-display font-extrabold tracking-tight">${esc(TRIP.name)}</p>
            <p class="text-[10px] uppercase tracking-[0.3em] text-slate-400">Seat ${m.seat} / ${String(n).padStart(2, "0")}</p>
          </div>
        </div>
      </div>`
    ).join("");

    dots.innerHTML = MEMBERS.map(
      (m, i) => `<button class="crew-dot" role="tab" aria-selected="false" aria-label="${esc(m.name)}" data-i="${i}">${avatar(m, "")}</button>`
    ).join("");

    const cards = $$(".crew-card", ring);
    const dotEls = $$(".crew-dot", dots);
    let angle = 0;
    let target = 0;
    let radius = 0;
    let active = -1;
    let dragging = false;
    let moved = 0;
    let lastX = 0;
    let velocity = 0;
    let visible = false;
    let hovering = false;
    let idleUntil = 0;
    let raf = 0;

    const layout = () => {
      const cw = parseFloat(getComputedStyle(stage).getPropertyValue("--cw")) || 220;
      radius = Math.round((cw / 2 / Math.tan(Math.PI / n)) * (innerWidth < 640 ? 1.08 : 1.3));
      stage.style.setProperty("--r", radius + "px");
      cards.forEach((c) => c.style.setProperty("--r", radius + "px"));
    };

    const renderDetail = (m) => {
      const roles = rolesOf(m.id);
      detail.innerHTML = `
        <div class="crew-detail-inner">
          <div class="flex items-center gap-4">
            ${avatar(m, "h-20 w-20 text-2xl")}
            <div>
              <p class="text-[11px] font-semibold uppercase tracking-[0.25em] text-amber-300">Seat ${m.seat} · Passenger</p>
              <h3 class="font-display text-2xl font-extrabold leading-tight sm:text-3xl">${esc(m.name)}</h3>
            </div>
          </div>
          <p class="mt-7 text-[11px] font-semibold uppercase tracking-[0.25em] text-slate-400">Responsibilities</p>
          <ul class="mt-3 grid gap-2.5">
            ${
              roles.length
                ? roles
                    .map(
                      ({ role, note }) => `
              <li class="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-3">
                <span class="grid h-10 w-10 flex-none place-items-center rounded-xl bg-gradient-to-br ${role.gradient} text-night-950">${ICONS[role.icon]}</span>
                <div>
                  <p class="font-semibold">${esc(role.title)}</p>
                  ${note ? `<p class="text-xs text-amber-300">${esc(note)}</p>` : `<p class="text-xs text-slate-400">Team of ${role.members.length}</p>`}
                </div>
              </li>`
                    )
                    .join("")
                : `<li class="text-slate-400">Along for the ride.</li>`
            }
          </ul>
        </div>`;
      hydratePhotos(detail);
    };

    const setActive = (i) => {
      active = i;
      cards.forEach((c, k) => c.classList.toggle("is-active", k === i));
      dotEls.forEach((d, k) => d.setAttribute("aria-selected", String(k === i)));
      renderDetail(MEMBERS[i]);
    };

    const render = () => {
      ring.style.transform = `translateZ(${-radius}px) rotateY(${angle}deg)`;
      cards.forEach((c, i) => {
        const rel = ((i * step + angle) * Math.PI) / 180;
        c.style.setProperty("--vis", (0.18 + 0.82 * ((Math.cos(rel) + 1) / 2) ** 1.4).toFixed(3));
      });
      const idx = (((Math.round(-angle / step) % n) + n) % n);
      if (idx !== active) setActive(idx);
    };

    const snap = (a) => Math.round(a / step) * step;
    const swish = (strength = 1) => sfx("whoosh", { volume: 0.3 + 0.2 * strength, rate: 0.9 + Math.random() * 0.25, throttle: 120 });
    const goTo = (i) => {
      swish();
      const base = -i * step;
      target = base + 360 * Math.round((angle - base) / 360);
      idleUntil = performance.now() + 9000;
      wake();
    };
    const nudge = (dir) => {
      swish();
      target = snap(target) - dir * step;
      idleUntil = performance.now() + 9000;
      wake();
    };

    const tick = () => {
      if (!dragging) {
        angle += (target - angle) * (reduceMotion ? 1 : 0.1);
        if (Math.abs(target - angle) < 0.01) angle = target;
      }
      render();
      raf = dragging || angle !== target ? requestAnimationFrame(tick) : 0;
    };
    const wake = () => {
      if (!raf) raf = requestAnimationFrame(tick);
    };

    // drag / swipe
    stage.addEventListener("pointerdown", (e) => {
      if (e.button !== 0) return;
      dragging = true;
      moved = 0;
      lastX = e.clientX;
      velocity = 0;
      stage.classList.add("dragging");
      stage.setPointerCapture(e.pointerId);
      wake();
    });
    stage.addEventListener("pointermove", (e) => {
      if (!dragging) return;
      const dx = e.clientX - lastX;
      lastX = e.clientX;
      moved += Math.abs(dx);
      const k = innerWidth < 640 ? 0.45 : 0.3;
      angle += dx * k;
      velocity = dx * k;
      target = angle;
    });
    const release = (e) => {
      if (!dragging) return;
      dragging = false;
      stage.classList.remove("dragging");
      idleUntil = performance.now() + 9000;
      if (moved < 6) {
        const card = document.elementFromPoint(e.clientX, e.clientY)?.closest(".crew-card");
        if (card) return goTo(+card.dataset.i);
      }
      target = snap(angle + velocity * 7);
      swish(Math.min(1, Math.abs(velocity) / 8));
      wake();
    };
    stage.addEventListener("pointerup", release);
    stage.addEventListener("pointercancel", release);
    stage.addEventListener("pointerenter", () => (hovering = true));
    stage.addEventListener("pointerleave", () => (hovering = false));
    stage.addEventListener("keydown", (e) => {
      if (e.key === "ArrowLeft") (e.preventDefault(), nudge(-1));
      if (e.key === "ArrowRight") (e.preventDefault(), nudge(1));
    });
    $("#crew-prev").addEventListener("click", () => nudge(-1));
    $("#crew-next").addEventListener("click", () => nudge(1));
    dotEls.forEach((d) => d.addEventListener("click", () => goTo(+d.dataset.i)));

    // autoplay while on screen and untouched
    if (!reduceMotion) {
      setInterval(() => {
        if (visible && !dragging && !hovering && performance.now() > idleUntil && !stage.contains(document.activeElement)) {
          target = snap(target) - step;
          wake();
        }
      }, 3800);
    }

    new IntersectionObserver(([en]) => {
      visible = en.isIntersecting;
      if (visible) wake();
    }).observe(stage);

    layout();
    render();
    addEventListener("resize", () => {
      layout();
      render();
    });
  };

  /* ---------------------------------------------------------------- roles */
  $("#roles-grid").innerHTML = ROLES.map(
    (r, i) => `
    <div class="role-wrap" data-reveal style="--delay:${i * 90}ms">
      <article class="tilt role-card" data-tilt="9">
        <div class="z-pop-1 flex items-start justify-between">
          <span class="role-icon bg-gradient-to-br ${r.gradient}">${ICONS[r.icon]}</span>
          <span class="role-num">${String(i + 1).padStart(2, "0")}</span>
        </div>
        <h3 class="z-pop-2 mt-4 font-display text-2xl font-extrabold">${esc(r.title)}</h3>
        <p class="z-pop-1 mt-2 text-sm text-slate-400">${esc(r.blurb)}</p>
        <ul class="z-pop-1 mt-6 grid gap-3">
          ${r.members
            .map((e) => {
              const m = byId[e.id];
              if (!m) return "";
              return `
            <li class="flex flex-wrap items-center gap-x-3 gap-y-1">
              ${avatar(m, "h-9 w-9 text-xs")}
              <span class="font-medium">${esc(m.name)}</span>
              ${e.note ? `<span class="rounded-full bg-amber-400/15 px-2.5 py-0.5 text-[11px] font-medium text-amber-300 ring-1 ring-amber-400/30">${esc(e.note)}</span>` : ""}
            </li>`;
            })
            .join("")}
        </ul>
        <div class="glare"></div>
      </article>
    </div>`
  ).join("");

  /* --------------------------------------------------------------- places */
  const STARS = Array.from({ length: 26 }, (_, i) => {
    const x = (i * 197) % 800;
    const y = (i * 71) % 150;
    return `<circle cx="${x}" cy="${y + 8}" r="${i % 4 === 0 ? 1.6 : 1}" fill="#fff" opacity="${0.35 + (i % 5) * 0.12}"/>`;
  }).join("");

  const FEATURES = {
    temple: `
      <g transform="translate(400 242)">
        <circle r="95" cy="-60" fill="url(#glow)" opacity=".55"/>
        <path fill="#120c26" d="M-62 0V-22h4c2-16 10-24 16-26 6 2 14 10 16 26h4V0Z"/>
        <path fill="#120c26" d="M22 0V-20h42V0Zm-4-20 25-16 25 16Z"/>
        <path fill="#140d2b" d="M-22 0v-38h5c1-32 7-54 13-66h8c6 12 12 34 13 66h5V0Z"/>
        <ellipse cy="-106" rx="11" ry="4" fill="#140d2b"/>
        <path fill="#140d2b" d="M-3-110 0-122 3-110Z"/>
        <path stroke="#140d2b" stroke-width="1.5" d="M0-122v-16"/>
        <path fill="#fb923c" d="M0-138 14-134 0-130Z"/>
        <g fill="#ffcf7a">
          <circle cx="-9" cy="-18" r="2"/><circle cx="9" cy="-18" r="2"/><circle cx="0" cy="-58" r="1.6"/>
          <circle cx="34" cy="-9" r="1.6"/><circle cx="52" cy="-9" r="1.6"/><circle cx="-42" cy="-11" r="1.6"/>
        </g>
      </g>`,
    city: `
      <g fill="#140d2b" transform="translate(250 242)">
        <rect x="0" y="-60" width="34" height="60"/><rect x="40" y="-96" width="28" height="96"/><rect x="74" y="-50" width="40" height="50"/>
        <rect x="120" y="-120" width="30" height="120"/><rect x="156" y="-70" width="44" height="70"/><rect x="206" y="-88" width="26" height="88"/>
        <rect x="238" y="-46" width="40" height="46"/>
      </g>`,
    beach: "",
    hills: "",
  };

  const placeArt = (p) => {
    if (p.image) {
      return `<div class="layer" style="--depth:10"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"></div>`;
    }
    const art = p.art || "temple";
    const sea = art === "beach";
    const svgOpen = `<svg viewBox="0 0 800 320" preserveAspectRatio="xMidYMax slice" aria-hidden="true">`;
    return `
      <div class="layer" style="--depth:3">${svgOpen}
        <defs>
          <linearGradient id="sky-${p.id}" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0" stop-color="#140f3a"/><stop offset=".55" stop-color="#7a2e5a"/><stop offset="1" stop-color="#ff9166"/>
          </linearGradient>
          <radialGradient id="glow"><stop offset="0" stop-color="#ffd29a"/><stop offset="1" stop-color="#ffd29a" stop-opacity="0"/></radialGradient>
        </defs>
        <rect width="800" height="320" fill="url(#sky-${p.id})"/>
        ${STARS}
        <circle cx="580" cy="205" r="130" fill="url(#glow)" opacity=".55"/>
        <circle cx="580" cy="205" r="44" fill="#ffd9a3"/>
        <path d="M150 90q8-7 16 0q8-7 16 0M205 70q6-5 12 0q6-5 12 0" stroke="#1b1236" stroke-width="2.5" fill="none" stroke-linecap="round"/>
      </svg></div>
      <div class="layer" style="--depth:7">${svgOpen}
        <path fill="#5b2d63" d="M0 230c80-40 150-55 230-35 70 17 110-25 190-33 80-7 140 33 220 23 70-9 120 5 160 11v124H0Z"/>
      </svg></div>
      <div class="layer" style="--depth:13">${svgOpen}
        ${
          sea
            ? `<path fill="#0e3a5a" d="M0 236h800v84H0Z"/><path stroke="#ffd29a" stroke-opacity=".5" stroke-width="3" fill="none" d="M520 250h120M540 262h80M500 275h160"/>
               <path fill="#e2b77a" d="M0 285c150-18 300-22 450-12 150 10 260 20 350 16v31H0Z"/>`
            : `<path fill="#2a1a48" d="M0 275c120-13 230-29 320-35 60-4 100-4 160 0 110 8 220 26 320 32v48H0Z"/>${FEATURES[art] || ""}`
        }
      </svg></div>
      <div class="layer" style="--depth:22">${svgOpen}
        <path fill="#0a0f24" d="M0 320v-36c40-5 70 5 100 16 30-10 60-2 90 20Zm620 0c40-24 100-32 180-38v38Z"/>
        <g stroke="#0a0f24" stroke-linecap="round" fill="none">
          <path stroke-width="7" d="M70 320c2-40 8-70 22-96"/>
          <path stroke-width="5" d="M92 224c-20-12-38-8-52 6M92 224c-6-20-22-28-40-26M92 224c14-16 32-18 48-8M92 224c20-4 34 6 40 22M92 224c-2 16-12 26-24 30"/>
          <path stroke-width="6" d="M740 320c-2-34-8-58-20-80"/>
          <path stroke-width="4.5" d="M720 240c-18-10-34-6-46 6M720 240c-4-18-18-26-34-24M720 240c12-14 28-16 42-8M720 240c18-4 30 6 34 20"/>
        </g>
      </svg></div>`;
  };

  const placeCard = (p, i) => `
    <div data-reveal class="${i === 0 ? "md:col-span-2" : ""}" style="--delay:${i * 90}ms">
      <article class="tilt place-card" data-tilt="${i === 0 ? 5 : 8}">
        <div class="place-art">
          ${placeArt(p)}
          <div class="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-night-800 to-transparent"></div>
          <span class="absolute left-5 top-5 rounded-full bg-night-950/60 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.25em] text-amber-200 backdrop-blur">Stop ${String(i + 1).padStart(2, "0")}</span>
        </div>
        <div class="p3d p-6 sm:p-8">
          <div class="z-pop-2">
            ${p.subtitle ? `<p class="text-xs font-semibold uppercase tracking-[0.2em] text-amber-300">${esc(p.subtitle)}</p>` : ""}
            <h3 class="mt-1 font-display text-3xl font-extrabold sm:text-4xl">${esc(p.name)}</h3>
          </div>
          <p class="z-pop-1 mt-3 max-w-2xl text-slate-300">${esc(p.description)}</p>
          <div class="z-pop-1 mt-5 flex flex-wrap gap-2">${(p.tags || []).map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div>
          ${
            p.tip
              ? `<p class="z-pop-1 mt-5 flex items-start gap-2.5 rounded-2xl border border-amber-300/20 bg-amber-300/[0.07] p-3.5 text-sm text-amber-100"><span class="mt-px flex-none text-amber-300">${ICONS.bulb}</span>${esc(p.tip)}</p>`
              : ""
          }
        </div>
        <div class="glare"></div>
      </article>
    </div>`;

  const soonCard = (i) => `
    <div data-reveal style="--delay:${(PLACES.length + i) * 90}ms">
      <article class="tilt place-card place-soon" data-tilt="10">
        <div class="p3d p-8 text-center">
          <div class="z-pop-3"><div class="soon-q">?</div></div>
          <p class="z-pop-2 mt-4 font-display text-2xl font-extrabold">Stop ${String(PLACES.length + i + 1).padStart(2, "0")}</p>
          <p class="z-pop-1 mt-2 text-sm text-slate-400">To be revealed — the Place team is scouting.</p>
          <div class="z-pop-1 mt-6 flex justify-center -space-x-2">${avatarStack(placeTeam)}</div>
        </div>
        <div class="glare"></div>
      </article>
    </div>`;

  $("#places-grid").innerHTML =
    PLACES.map(placeCard).join("") + Array.from({ length: UPCOMING }, (_, i) => soonCard(i)).join("");

  /* --------------------------------------------------------------- events */
  $("#events-grid").innerHTML = EVENTS.map((e, i) => {
    const off = i - (EVENTS.length - 1) / 2;
    const pip = (cls) => `<span class="pip ${cls}" aria-hidden="true"><span class="rank">${esc(e.rank)}</span><span class="suit">${e.suit}</span></span>`;
    const items = e.items || [];
    return `
    <div data-reveal style="--delay:${i * 110}ms">
      <div class="fan-item" style="--fan-r:${off * 5}deg; --fan-y:${Math.abs(off) * 14}px">
        <div class="flip" style="--c:${e.color}" role="button" tabindex="0" aria-pressed="false" aria-label="${esc(e.title)} — flip card for details">
          <div class="flip-inner">
            <div class="flip-face flip-front">
              ${pip("pip-tl")}${pip("pip-br")}
              <div class="flex h-full flex-col items-center justify-center p-4 text-center">
                <span class="card-emblem">${ICONS[e.icon] || ICONS.sparkles}</span>
                <p class="mt-4 font-display text-lg font-extrabold text-slate-900 sm:text-2xl">${esc(e.title)}</p>
                <p class="mt-1 text-xs text-slate-500 sm:text-sm">${esc(e.tagline)}</p>
              </div>
            </div>
            <div class="flip-face flip-back">
              <div class="flex h-full flex-col p-4 sm:p-5">
                <p class="text-[10px] font-semibold uppercase tracking-[0.25em]" style="color:var(--c)">${e.suit} In the deck</p>
                <p class="mt-1 font-display text-lg font-extrabold sm:text-2xl">${esc(e.title)}</p>
                ${
                  items.length
                    ? `<ul class="mt-3 grid gap-1.5 sm:gap-2">${items
                        .map(
                          (it) =>
                            `<li class="flex items-center gap-2 rounded-xl bg-white/[0.06] px-3 py-1.5 text-sm font-medium ring-1 ring-white/10 sm:py-2"><span style="color:var(--c)">${e.suit}</span>${esc(it)}</li>`
                        )
                        .join("")}</ul>`
                    : `<p class="mt-3 text-sm text-slate-300">${esc(e.description || e.tagline)}</p>`
                }
                <div class="mt-auto hidden pt-4 sm:block">
                  <p class="text-[10px] uppercase tracking-[0.2em] text-slate-400">Hosted by the Event team</p>
                  <div class="mt-2 flex -space-x-2">${avatarStack(eventTeam, "h-8 w-8 text-[10px]")}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>`;
  }).join("");

  const EVENT_SOUNDS = { pop: ["ping", { rate: 1.45 }], shuffle: ["shuffle", {}], slap: ["slap", {}], shutter: ["shutter", {}] };
  $$(".flip").forEach((card, i) => {
    const flipSound = (toBack) => {
      sfx("flip", { volume: toBack ? 0.5 : 0.3, rate: toBack ? 1 : 1.12, throttle: 150 });
      const [name, opts] = EVENT_SOUNDS[EVENTS[i].sound] || [];
      if (toBack && name) sfx(name, { volume: 0.55, delay: 0.16, throttle: 300, ...opts });
    };
    const toggle = () => {
      const on = !card.classList.contains("flipped");
      card.classList.toggle("flipped", on);
      card.setAttribute("aria-pressed", String(on));
      flipSound(on);
    };
    // hover already flips on mouse devices; clicks/taps/keys toggle a sticky flip
    if (finePointer) {
      card.addEventListener("pointerenter", () => !card.classList.contains("flipped") && flipSound(true));
      card.addEventListener("pointerleave", () => !card.classList.contains("flipped") && flipSound(false));
    }
    card.addEventListener("click", () => !finePointer && toggle());
    card.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") (e.preventDefault(), toggle());
    });
  });

  /* ----------------------------------------------------- hover sounds */
  $$(".role-card").forEach((el) => el.addEventListener("pointerenter", () => sfx("tick", { volume: 0.22, throttle: 120 })));
  $$(".place-card").forEach((el) =>
    el.addEventListener("pointerenter", () =>
      el.classList.contains("place-soon") ? sfx("ping", { volume: 0.22, rate: 0.7, throttle: 400 }) : sfx("bell", { volume: 0.4, throttle: 6000 })
    )
  );
  $("#ticket .ticket").addEventListener("click", () => sfx("stamp", { volume: 0.6, throttle: 250 }));

  /* ---------------------------------------------------------------- footer */
  $("#footer-crew").innerHTML = MEMBERS.map(
    (m) => `<span class="inline-flex items-center gap-2">${avatar(m, "h-7 w-7 text-[10px]")}${esc(m.name)}</span>`
  ).join("");

  /* ------------------------------------------------------- tilt handling */
  const initTilt = () => {
    if (reduceMotion || !finePointer) return;
    $$("[data-tilt]").forEach((el) => {
      const max = parseFloat(el.dataset.tilt) || 8;
      let rect = null;
      const set = (k, v) => el.style.setProperty(k, v);
      el.addEventListener("pointerenter", () => {
        rect = el.getBoundingClientRect();
        el.classList.add("tilting");
      });
      el.addEventListener("pointermove", (e) => {
        rect ||= el.getBoundingClientRect();
        const x = (e.clientX - rect.left) / rect.width;
        const y = (e.clientY - rect.top) / rect.height;
        set("--ry", `${((x - 0.5) * max * 2).toFixed(2)}deg`);
        set("--rx", `${((0.5 - y) * max * 2).toFixed(2)}deg`);
        set("--gx", `${(x * 100).toFixed(1)}%`);
        set("--gy", `${(y * 100).toFixed(1)}%`);
        set("--px", ((0.5 - x) * 2).toFixed(3));
        set("--py", ((0.5 - y) * 2).toFixed(3));
      });
      el.addEventListener("pointerleave", () => {
        rect = null;
        el.classList.remove("tilting");
        set("--rx", "0deg");
        set("--ry", "0deg");
        set("--px", "0");
        set("--py", "0");
      });
    });
  };

  /* -------------------------------------------------------- scroll reveal */
  const revealIO = new IntersectionObserver(
    (entries) =>
      entries.forEach((en) => {
        if (!en.isIntersecting) return;
        en.target.classList.add("in-view");
        if (en.target.id === "stats") runCounters();
        revealIO.unobserve(en.target);
      }),
    { threshold: 0.12, rootMargin: "0px 0px -6% 0px" }
  );
  $$("[data-reveal]").forEach((el) => revealIO.observe(el));

  /* ------------------------------------------------------------------ nav */
  const nav = $("#nav");
  const navLinks = $("#nav-links");
  const indicator = $(".nav-indicator", navLinks);
  const menuBtn = $("#menu-btn");
  const board = $("#mobile-menu");
  let current = "home";

  $("#board-crew").innerHTML = avatarStack(MEMBERS, "h-8 w-8 text-[10px]");

  // the highlight slides between links like a train between stations
  let lastX = null;
  const moveIndicator = (link) => {
    if (!link || !navLinks.offsetParent) return navLinks.style.setProperty("--io", 0);
    const x = link.offsetLeft;
    if (lastX !== null && x !== lastX) indicator.dataset.dir = x > lastX ? "right" : "left";
    lastX = x;
    navLinks.style.setProperty("--ix", x + "px");
    navLinks.style.setProperty("--iw", link.offsetWidth + "px");
    navLinks.style.setProperty("--io", 1);
  };
  const activeLink = () => $(`.nav-link[href="#${current}"]`, navLinks);
  $$(".nav-link", navLinks).forEach((a) => {
    a.addEventListener("pointerenter", () => moveIndicator(a));
    a.addEventListener("focus", () => moveIndicator(a));
  });
  navLinks.addEventListener("pointerleave", () => moveIndicator(activeLink()));
  navLinks.addEventListener("focusout", () => moveIndicator(activeLink()));

  const setCurrent = (id) => {
    current = id;
    $$(".nav-link, .board-link").forEach((a) => {
      if (a.getAttribute("href") === "#" + id) a.setAttribute("aria-current", "location");
      else a.removeAttribute("aria-current");
    });
    $$(".board-link", board).forEach((a) => {
      $(".board-status", a).innerHTML = a.hasAttribute("aria-current") ? "● Now" : ICONS.arrow;
    });
    moveIndicator(activeLink());
    window.SFX && window.SFX.enterSection(id);
  };

  // mobile departure board
  const isOpen = () => board.classList.contains("open");
  const setMenu = (open) => {
    board.classList.toggle("open", open);
    board.setAttribute("aria-hidden", String(!open));
    nav.classList.toggle("menu-open", open);
    menuBtn.setAttribute("aria-expanded", String(open));
    menuBtn.setAttribute("aria-label", open ? "Close menu" : "Open menu");
    document.body.style.overflow = open ? "hidden" : "";
    if (open) setTimeout(() => $(".board-link", board).focus({ preventScroll: true }), 300);
  };
  menuBtn.addEventListener("click", () => {
    const open = !isOpen();
    setMenu(open);
    open ? sfx("flap", { volume: 0.5 }) : sfx("tick", { volume: 0.3 });
  });
  $$(".nav-link, .board-link, .nav-brand").forEach((a) => a.addEventListener("click", () => sfx("click", { volume: 0.5 })));
  $(".nav-ticket").addEventListener("click", () => sfx("stamp", { volume: 0.55 }));
  $$(".board-link", board).forEach((a) => a.addEventListener("click", () => setMenu(false)));
  addEventListener("keydown", (e) => {
    if (e.key === "Escape" && isOpen()) {
      setMenu(false);
      menuBtn.focus();
    }
  });
  matchMedia("(min-width: 1024px)").addEventListener("change", (e) => {
    if (e.matches && isOpen()) setMenu(false);
    moveIndicator(activeLink());
  });

  const sectionIO = new IntersectionObserver(
    (entries) => entries.forEach((en) => en.isIntersecting && setCurrent(en.target.id)),
    { rootMargin: "-45% 0px -50% 0px" }
  );
  ["home", "journey", "crew", "roles", "places", "events", "faq"].forEach((id) => sectionIO.observe(document.getElementById(id)));
  setCurrent("home");
  new IntersectionObserver(([en]) => window.SFX && window.SFX.enterSection(en.isIntersecting ? "footer" : current), {
    threshold: 0.6,
  }).observe($("#footer"));

  /* ---------------------------------------------------------------- sound */
  const soundBtn = $("#sound-btn");
  const syncSound = () => {
    const on = !!(window.SFX && window.SFX.enabled);
    soundBtn.setAttribute("aria-pressed", String(on));
    soundBtn.setAttribute("aria-label", on ? "Turn sound off" : "Turn sound on");
    document.documentElement.classList.toggle("sound-on", on);
  };
  if (window.SFX) {
    addEventListener("sound:change", syncSound);
    soundBtn.addEventListener("click", () => window.SFX.toggle());
    addEventListener("keydown", (e) => {
      const typing = /^(input|textarea|select)$/i.test(e.target.tagName);
      if ((e.key === "m" || e.key === "M") && !e.ctrlKey && !e.metaKey && !e.altKey && !typing)
        window.SFX.toggle();
    });
    // tap the landing scene to sound the horn (the 3D headlights flash with it)
    $("#home").addEventListener("click", (e) => !e.target.closest("a, button") && sfx("horn", { volume: 0.9, throttle: 2500 }));
    $$("#home .btn-primary, #home .btn-ghost, #crew-prev, #crew-next").forEach((b) =>
      b.addEventListener("pointerenter", () => sfx("tick", { volume: 0.18 }))
    );
  } else {
    soundBtn.hidden = true;
  }

  let ticking = false;
  const onScroll = () => {
    if (ticking) return;
    ticking = true;
    requestAnimationFrame(() => {
      nav.classList.toggle("scrolled", scrollY > 40);
      const max = document.documentElement.scrollHeight - innerHeight;
      nav.style.setProperty("--progress", max > 0 ? Math.min(1, scrollY / max).toFixed(4) : "0");
      updateRoute();
      ticking = false;
    });
  };
  addEventListener("scroll", onScroll, { passive: true });
  addEventListener("resize", () => {
    routeGeo = null;
    onScroll();
    moveIndicator(activeLink());
  });

  /* --------------------------------------------------------------- boot */
  hydrateIcons();
  initCrew();
  initTilt();
  hydratePhotos();
  onScroll();
  document.fonts?.ready.then(() => {
    routeGeo = null;
    onScroll();
    moveIndicator(activeLink());
  });

  // No loading screen: content shows at once (faster for visitors, no interstitial for search
  // engines); the 3D scene fades in over the hero backdrop when it's ready.
  const root = document.documentElement;
  root.classList.add("ready");

  // Sound is ON by default. Browsers only allow audio after the visitor's first tap/click/key,
  // so it starts right then (or immediately if the browser already allows it).
  const chip = $("#sound-chip");
  const hideChip = () => {
    root.classList.remove("sound-pending");
    chip.classList.remove("show");
    setTimeout(() => (chip.hidden = true), 400);
  };
  if (window.SFX) {
    const SFX = window.SFX;
    $("#sound-chip-off").addEventListener("click", () => {
      SFX.disable();
      hideChip();
    });
    addEventListener("sound:change", () => SFX.enabled && hideChip());
    (async () => {
      if (SFX.pref() === "off") return; // this visitor muted it earlier
      if (await SFX.canAutoplay()) return SFX.enable({ intro: true });
      chip.hidden = false;
      requestAnimationFrame(() => chip.classList.add("show"));
      root.classList.add("sound-pending");
      SFX.unlockOnInteraction();
    })();
  }
};

// let the browser paint the page first, then bring it to life
// (the timer covers background tabs, which don't paint until they're shown)
let booted = false;
const start = () => !booted && ((booted = true), boot());
requestAnimationFrame(() => setTimeout(start, 0));
setTimeout(start, 1000);
