/* Generated by tools/photos.js (npm run photos). Optimized member photos. */
window.PHOTOS = {
  "durga": "assets/members/web/durga.webp",
  "manash": "assets/members/web/manash.webp",
  "ashish": "assets/members/web/ashish.webp",
  "amit": "assets/members/web/amit.webp",
  "akash": "assets/members/web/akash.webp",
  "somesh": "assets/members/web/somesh.webp",
  "sandeep": "assets/members/web/sandeep.webp"
};
