#!/usr/bin/env node
/* ==========================================================================
   VIZAG EXPRESS — PHOTO OPTIMIZER
   Makes small, fast WebP versions of the member photos (the site shows them
   at 40–220 px, so multi-megapixel originals just slow the page down).
     assets/members/<id>.(jpg|jpeg|png|webp)  →  assets/members/web/<id>.webp
   and writes js/photos.js so the site loads those directly (no guessing).
   Originals are never modified.
   Usage:  npm run photos        (after adding or changing a photo)
   ========================================================================== */
"use strict";
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const sharp = require("sharp");

const ROOT = path.join(__dirname, "..");
const SIZE = 480; // square, enough for the 220 px crew cards on 2× screens
const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(ROOT, "js/data.js"), "utf8"), sandbox);
const { MEMBERS } = sandbox.window;

(async () => {
  const outDir = path.join(ROOT, "assets/members/web");
  fs.mkdirSync(outDir, { recursive: true });
  const map = {};
  for (const m of MEMBERS) {
    const src = m.photo
      ? path.join(ROOT, m.photo)
      : ["jpg", "jpeg", "png", "webp"].map((e) => path.join(ROOT, `assets/members/${m.id}.${e}`)).find((p) => fs.existsSync(p));
    if (!src || !fs.existsSync(src)) {
      console.log(`  – ${m.nick}: no photo yet`);
      map[m.id] = null; // tells the site not to look for one
      continue;
    }
    const out = path.join(outDir, `${m.id}.webp`);
    await sharp(src)
      .rotate() // respect phone EXIF orientation
      .resize(SIZE, SIZE, { fit: "cover", position: sharp.strategy.attention }) // smart crop keeps the face
      .webp({ quality: 78 })
      .toFile(out);
    const before = fs.statSync(src).size;
    const after = fs.statSync(out).size;
    map[m.id] = `assets/members/web/${m.id}.webp`;
    console.log(`  ✓ ${m.nick}: ${Math.round(before / 1024)} KB → ${Math.round(after / 1024)} KB`);
  }
  fs.writeFileSync(
    path.join(ROOT, "js/photos.js"),
    `/* Generated by tools/photos.js (npm run photos). Optimized member photos. */\nwindow.PHOTOS = ${JSON.stringify(map, null, 2)};\n`
  );
  console.log(`✓ js/photos.js (${Object.values(map).filter(Boolean).length} photos)`);
})();
